// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/wintbiit/rmtv/ent/post"
	"github.com/wintbiit/rmtv/ent/predicate"
)

// PostUpdate is the builder for updating Post entities.
type PostUpdate struct {
	config
	hooks    []Hook
	mutation *PostMutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdate) Where(ps ...predicate.Post) *PostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSource sets the "source" field.
func (_u *PostUpdate) SetSource(v string) *PostUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *PostUpdate) SetNillableSource(v *string) *PostUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetPicture sets the "picture" field.
func (_u *PostUpdate) SetPicture(v string) *PostUpdate {
	_u.mutation.SetPicture(v)
	return _u
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (_u *PostUpdate) SetNillablePicture(v *string) *PostUpdate {
	if v != nil {
		_u.SetPicture(*v)
	}
	return _u
}

// ClearPicture clears the value of the "picture" field.
func (_u *PostUpdate) ClearPicture() *PostUpdate {
	_u.mutation.ClearPicture()
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdate) SetTitle(v string) *PostUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdate) SetNillableTitle(v *string) *PostUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PostUpdate) SetDescription(v string) *PostUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PostUpdate) SetNillableDescription(v *string) *PostUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *PostUpdate) SetTags(v []string) *PostUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *PostUpdate) AppendTags(v []string) *PostUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetPubDate sets the "pub_date" field.
func (_u *PostUpdate) SetPubDate(v time.Time) *PostUpdate {
	_u.mutation.SetPubDate(v)
	return _u
}

// SetNillablePubDate sets the "pub_date" field if the given value is not nil.
func (_u *PostUpdate) SetNillablePubDate(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetPubDate(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *PostUpdate) SetAuthor(v string) *PostUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *PostUpdate) SetNillableAuthor(v *string) *PostUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetAuthorURL sets the "author_url" field.
func (_u *PostUpdate) SetAuthorURL(v string) *PostUpdate {
	_u.mutation.SetAuthorURL(v)
	return _u
}

// SetNillableAuthorURL sets the "author_url" field if the given value is not nil.
func (_u *PostUpdate) SetNillableAuthorURL(v *string) *PostUpdate {
	if v != nil {
		_u.SetAuthorURL(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *PostUpdate) SetURL(v string) *PostUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *PostUpdate) SetNillableURL(v *string) *PostUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetExtra sets the "extra" field.
func (_u *PostUpdate) SetExtra(v any) *PostUpdate {
	_u.mutation.SetExtra(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PostUpdate) SetCreatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCreatedAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdate) SetUpdatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillableUpdatedAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdate) Mutation() *PostMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := post.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Post.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	return nil
}

func (_u *PostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(post.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Picture(); ok {
		_spec.SetField(post.FieldPicture, field.TypeString, value)
	}
	if _u.mutation.PictureCleared() {
		_spec.ClearField(post.FieldPicture, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(post.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(post.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, post.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.PubDate(); ok {
		_spec.SetField(post.FieldPubDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(post.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorURL(); ok {
		_spec.SetField(post.FieldAuthorURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(post.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extra(); ok {
		_spec.SetField(post.FieldExtra, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(post.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostUpdateOne is the builder for updating a single Post entity.
type PostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMutation
}

// SetSource sets the "source" field.
func (_u *PostUpdateOne) SetSource(v string) *PostUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSource(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetPicture sets the "picture" field.
func (_u *PostUpdateOne) SetPicture(v string) *PostUpdateOne {
	_u.mutation.SetPicture(v)
	return _u
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillablePicture(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetPicture(*v)
	}
	return _u
}

// ClearPicture clears the value of the "picture" field.
func (_u *PostUpdateOne) ClearPicture() *PostUpdateOne {
	_u.mutation.ClearPicture()
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdateOne) SetTitle(v string) *PostUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableTitle(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PostUpdateOne) SetDescription(v string) *PostUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableDescription(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *PostUpdateOne) SetTags(v []string) *PostUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *PostUpdateOne) AppendTags(v []string) *PostUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetPubDate sets the "pub_date" field.
func (_u *PostUpdateOne) SetPubDate(v time.Time) *PostUpdateOne {
	_u.mutation.SetPubDate(v)
	return _u
}

// SetNillablePubDate sets the "pub_date" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillablePubDate(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetPubDate(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *PostUpdateOne) SetAuthor(v string) *PostUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableAuthor(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetAuthorURL sets the "author_url" field.
func (_u *PostUpdateOne) SetAuthorURL(v string) *PostUpdateOne {
	_u.mutation.SetAuthorURL(v)
	return _u
}

// SetNillableAuthorURL sets the "author_url" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableAuthorURL(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetAuthorURL(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *PostUpdateOne) SetURL(v string) *PostUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableURL(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetExtra sets the "extra" field.
func (_u *PostUpdateOne) SetExtra(v any) *PostUpdateOne {
	_u.mutation.SetExtra(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PostUpdateOne) SetCreatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCreatedAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdateOne) SetUpdatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableUpdatedAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdateOne) Mutation() *PostMutation {
	return _u.mutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdateOne) Where(ps ...predicate.Post) *PostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostUpdateOne) Select(field string, fields ...string) *PostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Post entity.
func (_u *PostUpdateOne) Save(ctx context.Context) (*Post, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdateOne) SaveX(ctx context.Context) *Post {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := post.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Post.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	return nil
}

func (_u *PostUpdateOne) sqlSave(ctx context.Context) (_node *Post, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Post.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, post.FieldID)
		for _, f := range fields {
			if !post.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != post.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(post.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Picture(); ok {
		_spec.SetField(post.FieldPicture, field.TypeString, value)
	}
	if _u.mutation.PictureCleared() {
		_spec.ClearField(post.FieldPicture, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(post.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(post.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, post.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.PubDate(); ok {
		_spec.SetField(post.FieldPubDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(post.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorURL(); ok {
		_spec.SetField(post.FieldAuthorURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(post.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extra(); ok {
		_spec.SetField(post.FieldExtra, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(post.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Post{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
